openapi: 3.0.3
info:
    title: Schrodinger's Box
    version: 1.0.0
servers:
-   url: 'http://localhost:8080/api'
paths:
    /auth/token:
        post:
            summary: create a token with a redirection url to authenticate user
            operationId: auth.create_token
            tags:
            -   auth
            requestBody:
                required: true
                content:
                    'application/vnd.api+json':
                        schema: 
                            type: object
                            required:
                            -   data
                            properties:
                                data:
                                    $ref: '#/components/schemas/Token'
            responses:
                '201':
                    description: token created, redirect user to login
                    content:
                        'application/vnd.api+json':
                            schema: 
                                type: object
                                required:
                                -   data
                                properties:
                                    data:
                                        $ref: '#/components/schemas/Token'
                default:
                    description: unexpected error occured
                    content:
                        'application/vnd.api+json':
                            schema:
                                $ref: '#/components/x-definitions/Errors'
components:
    schemas:
        Token:
            type: object
            required:
                - type
            properties:
                type:
                    description: type of Token object, which is just `token`
                    type: string
                    enum:
                    -   token
                id:
                    $ref: '#/components/x-definitions/ID'
                attributes:
                    type: object
                    properties:
                        status:
                            description: status of the token
                            type: string
                            enum:
                                - created
                                - active
                                - expired
                                - destroyed
                        nus_identifier:
                            $ref: '#/components/x-definitions/NUSIdentifier'
                links:
                    type: object
                    properties:
                        auth:
                            description: URL for users to prove their claimed identities
                            type: string
        User:
            type: object
            required:
            -   type
            -   id
            -   attributes
            properties:
                type:
                    description: type of User object, which is just `user`
                    type: string
                    enum:
                    -   user
                id:
                    $ref: '#/components/x-definitions/ID'
                attributes:
                    type: object
                    required:
                    -   nickname
                    -   nus_identifier
                    properties:
                        nickname:
                            description: a nickname defined by the user when it is first created
                            type: string
                        nus_identifier:
                            $ref: '#/components/x-definitions/NUSIdentifier'
                        email:
                            description: email of the user, whether returning it depends on user's privacy setting
                            type: string
                            format: email
                        fullname:
                            description: full name of the user, whether returning it depends on user's privacy setting
                            type: string
        Event:
            type: object
            required:
            -   type
            -   id
            -   attributes
            properties:
                type:
                    description: type of Event object, which is just `event`
                    type: string
                    enum:
                    -   event
                id:
                    $ref: '#/components/x-definitions/ID'
                attributes:
                    type: object
                    required:
                    -   title
                    -   time_begin
                    -   time_end
                    -   organizer
                    -   location
                    -   type
                    properties:
                        title:
                            description: title of the event which will be showned at places like search results
                            type: string
                        time_begin:
                            $ref: '#/components/x-definitions/DateTime'
                        time_end:
                            $ref: '#/components/x-definitions/DateTime'
                        organizer:
                            $ref: '#/components/x-definitions/NUSIdentifier'
                        location:
                            oneOf:
                            -   $ref: '#/components/x-definitions/LocationOnline'
                            -   $ref: '#/components/x-definitions/LocationPhysical'
                        type:
                            description: type of this event
                            type: string       
    # definitions of data types
    x-definitions:
        Errors:
            type: array
            items:
                type: object
                required:
                -   status
                -   code
                -   title
                properties:
                    status:
                        # error code should only be 4XX or 5XX for an error object
                        description: the HTTP status code applicable to this problem in string
                        type: string
                        pattern: ^[4,5]\d\d$
                    code:
                        description: an application-specific error code
                        type: string
                    title:
                        description: a short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem
                        type: string
                    detail:
                        description: a human-readable explanation specific to this occurrence of the problem
        NUSIdentifier:
            description: a linked NUSNET id
            type: string
            pattern: ^e\d{7}$
        ID:
            description: primary key of resource objects, unique within the scope of a certain resource
            type: integer
            # int64 corresponds to BIGINT in MySQL
            format: int64
        DateTime:
            description: a specfic time at a specific date, defined by RFC3339 date-time
            type: string
            format: date-time
        LocationOnline:
            description: an object representing an online location
            type: object
            required:
            -   type
            -   platform
            -   link
            properties:
                type:
                    description: type of this location object, which is just `online`
                    type: string
                    enum:
                    -   online
                platform:
                    description: the platform for online event to be held
                    type: string
                link:
                    description: the url or any information like room number linked to the platform and the room, if any
                    type: string
        LocationPhysical:
            description: a physical location located in Singapore
            required:
            -   type
            -   zip_code
            -   address
            properties:
                type:
                    description: type of this location object, which is just `physical`
                    type: string
                    enum:
                    -   physical
                zip_code:
                    description: a Singapore 6-digit postal code represented in a string
                    type: string
                    pattern: ^[0-8]\d{5}$
                address:
                    description: an address with block number
                    type: string
                building:
                    description: name of the building at this address
                    type: string
                unit:
                    description: a unit number with two parts separated by a hyphen
                    type: string
                    format: ^[A-Z0-9]\d*-\d+[A-Z]*$
    examples:
        LocationOnline1:
            summary: example for an online location with url
            value:
                type: online
                platform: Telegram
                link: https://t.me/joinchat/AAAAAE9B8u_something
        LocationOnline2:
            summary: example for an online location with custom information like room number
            value:
                type: online
                platform: Telegram
                link: https://t.me/joinchat/AAAAAE9B8u_something
        LocationPhysical1:
            summary: a physical location example with building name and without unit number
            value:
                type: physical
                zip_code: 117561
                address: 2 Sports Drive 1
                building: University Sports Centre
        LocationPhysical2:
            summary: a HDB flat address example
            value:
                type: physical
                zip_code: 120329
                address: 329 Clementi Ave 2
                unit: 10-13